// flow-typed signature: df337e6ce7024b59f3c5c0bcc323fab3
// flow-typed version: <<STUB>>/object-path-immutable_v^0.5.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-path-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-path-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-path-immutable/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-path-immutable/index' {
  declare module.exports: $Exports<'object-path-immutable'>;
}
declare module 'object-path-immutable/index.js' {
  declare module.exports: $Exports<'object-path-immutable'>;
}
declare module 'object-path-immutable/test.js' {
  declare module.exports: $Exports<'object-path-immutable/test'>;
}
